version: "3.8"

services:
  postgres:
    image: m.daocloud.io/docker.io/library/postgres:15-alpine
    container_name: oraura-postgres
    environment:
      POSTGRES_DB: oraura_db
      POSTGRES_USER: oraura
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U oraura -d oraura_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: m.daocloud.io/docker.io/library/redis:7-alpine
    container_name: oraura-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: oraura-backend
    ports:
      - "8080:8080"
    environment:
      ORAURA_DATABASE_HOST: postgres
      ORAURA_DATABASE_PORT: 5432
      ORAURA_DATABASE_USER: oraura
      ORAURA_DATABASE_PASSWORD: password
      ORAURA_DATABASE_NAME: oraura_db
      ORAURA_JWT_SECRET: docker-secret-key
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
