server:
  host: 0.0.0.0
  port: 8080
  mode: debug
  read_timeout: 60s
  write_timeout: 60s

database:
  driver: postgres
  host: localhost
  port: 5432
  user: oraura
  password: password
  name: oraura_db
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 5m

jwt:
  secret: dev-super-secret-jwt-key-for-development-only
  access_token_expire: 1h
  refresh_token_expire: 720h

super_admin:
  email: admin@oraura.app
  username: superadmin
  password: DevAdmin123!

redis:
  host: localhost
  port: 6379
  password: ""
  database: 0
  pool_size: 10

logging:
  level: info
  format: json
  output: stdout
  file_path: logs/app.log
